//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IridiumGoManager.IridiumGo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://iridiumgo.lan/sdk/", ConfigurationName="IridiumGo.sdk")]
    public interface sdk {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iridiumgo.lan/sdk/getVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="versionNumber")]
        IridiumGoManager.IridiumGo.sdk_version_t getVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iridiumgo.lan/sdk/getVersion", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="versionNumber")]
        System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.sdk_version_t> getVersionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iridiumgo.lan/sdk/getUserDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="login")]
        IridiumGoManager.IridiumGo.sdk_user_details_response_t getUserDetails(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iridiumgo.lan/sdk/getUserDetails", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="login")]
        System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.sdk_user_details_response_t> getUserDetailsAsync(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials);
        
        // CODEGEN: Parameter 'request' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://iridiumgo.lan/sdk/getStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="statusOutput")]
        IridiumGoManager.IridiumGo.getStatusResponse getStatus(IridiumGoManager.IridiumGo.getStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iridiumgo.lan/sdk/getStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.getStatusResponse> getStatusAsync(IridiumGoManager.IridiumGo.getStatusRequest request);
        
        // CODEGEN: Parameter 'reqList' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://iridiumgo.lan/sdk/getSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="configs")]
        IridiumGoManager.IridiumGo.getSettingsResponse getSettings(IridiumGoManager.IridiumGo.getSettingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iridiumgo.lan/sdk/getSettings", ReplyAction="*")]
        System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.getSettingsResponse> getSettingsAsync(IridiumGoManager.IridiumGo.getSettingsRequest request);
        
        // CODEGEN: Parameter 'setList' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://iridiumgo.lan/sdk/setSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="setSettingsResponse")]
        IridiumGoManager.IridiumGo.setSettingsResponse setSettings(IridiumGoManager.IridiumGo.setSettingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iridiumgo.lan/sdk/setSettings", ReplyAction="*")]
        System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.setSettingsResponse> setSettingsAsync(IridiumGoManager.IridiumGo.setSettingsRequest request);
        
        // CODEGEN: Parameter 'taskList' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://iridiumgo.lan/sdk/performTask", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="parameters")]
        IridiumGoManager.IridiumGo.performTaskResponse performTask(IridiumGoManager.IridiumGo.performTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iridiumgo.lan/sdk/performTask", ReplyAction="*")]
        System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.performTaskResponse> performTaskAsync(IridiumGoManager.IridiumGo.performTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iridiumgo.lan/sdk/getUserList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getUserListResponse")]
        IridiumGoManager.IridiumGo.sdk_user_getList_Response_t getUserList(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iridiumgo.lan/sdk/getUserList", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getUserListResponse")]
        System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.sdk_user_getList_Response_t> getUserListAsync(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iridiumgo.lan/sdk/addModifyUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="addModifyUserResponse")]
        IridiumGoManager.IridiumGo.sdk_user_add_modify_remove_Response_t addModifyUser(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, IridiumGoManager.IridiumGo.sdk_user_t user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iridiumgo.lan/sdk/addModifyUser", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="addModifyUserResponse")]
        System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.sdk_user_add_modify_remove_Response_t> addModifyUserAsync(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, IridiumGoManager.IridiumGo.sdk_user_t user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iridiumgo.lan/sdk/removeUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="removeUserResponse")]
        IridiumGoManager.IridiumGo.sdk_user_add_modify_remove_Response_t removeUser(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iridiumgo.lan/sdk/removeUser", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="removeUserResponse")]
        System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.sdk_user_add_modify_remove_Response_t> removeUserAsync(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iridiumgo.lan/sdk/getContactList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="contactList")]
        IridiumGoManager.IridiumGo.sdk_contacts_getList_Response_t getContactList(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iridiumgo.lan/sdk/getContactList", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="contactList")]
        System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.sdk_contacts_getList_Response_t> getContactListAsync(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iridiumgo.lan/sdk/addNewContact", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="addContactResult")]
        IridiumGoManager.IridiumGo.sdk_contact_add_modify_remove_Response_t addNewContact(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, string name, string number, bool isFavourite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iridiumgo.lan/sdk/addNewContact", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="addContactResult")]
        System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.sdk_contact_add_modify_remove_Response_t> addNewContactAsync(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, string name, string number, bool isFavourite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iridiumgo.lan/sdk/modifyContact", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        IridiumGoManager.IridiumGo.sdk_contact_add_modify_remove_Response_t modifyContact(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, IridiumGoManager.IridiumGo.sdk_contact_t contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iridiumgo.lan/sdk/modifyContact", ReplyAction="*")]
        System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.sdk_contact_add_modify_remove_Response_t> modifyContactAsync(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, IridiumGoManager.IridiumGo.sdk_contact_t contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iridiumgo.lan/sdk/removeContact", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        IridiumGoManager.IridiumGo.sdk_contact_add_modify_remove_Response_t removeContact(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, int contactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iridiumgo.lan/sdk/removeContact", ReplyAction="*")]
        System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.sdk_contact_add_modify_remove_Response_t> removeContactAsync(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, int contactID);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iridiumgo.lan/sdk/")]
    public partial class sdk_version_t : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apiVersionField;
        
        private string firmwareVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apiVersion {
            get {
                return this.apiVersionField;
            }
            set {
                this.apiVersionField = value;
                this.RaisePropertyChanged("apiVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string firmwareVersion {
            get {
                return this.firmwareVersionField;
            }
            set {
                this.firmwareVersionField = value;
                this.RaisePropertyChanged("firmwareVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iridiumgo.lan/sdk/")]
    public partial class sdk_contact_add_modify_remove_Response_t : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iridiumgo.lan/sdk/")]
    public partial class sdk_contact_t : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private string numberField;
        
        private bool isFavouriteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool isFavourite {
            get {
                return this.isFavouriteField;
            }
            set {
                this.isFavouriteField = value;
                this.RaisePropertyChanged("isFavourite");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iridiumgo.lan/sdk/")]
    public partial class sdk_contacts_getList_Response_t : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorField;
        
        private string errorMessageField;
        
        private sdk_contact_t[] contactsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contacts", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public sdk_contact_t[] contacts {
            get {
                return this.contactsField;
            }
            set {
                this.contactsField = value;
                this.RaisePropertyChanged("contacts");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iridiumgo.lan/sdk/")]
    public partial class sdk_user_add_modify_remove_Response_t : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iridiumgo.lan/sdk/")]
    public partial class sdk_user_getList_Response_t : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorField;
        
        private string errorMessageField;
        
        private sdk_user_t[] usersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("users", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public sdk_user_t[] users {
            get {
                return this.usersField;
            }
            set {
                this.usersField = value;
                this.RaisePropertyChanged("users");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iridiumgo.lan/sdk/")]
    public partial class sdk_user_t : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private bool outgoingCallField;
        
        private int userPriorityField;
        
        private bool sendSmsField;
        
        private bool receiveSmsField;
        
        private bool canAccessTwitterField;
        
        private bool trackingField;
        
        private bool isAdminField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool outgoingCall {
            get {
                return this.outgoingCallField;
            }
            set {
                this.outgoingCallField = value;
                this.RaisePropertyChanged("outgoingCall");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int userPriority {
            get {
                return this.userPriorityField;
            }
            set {
                this.userPriorityField = value;
                this.RaisePropertyChanged("userPriority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool sendSms {
            get {
                return this.sendSmsField;
            }
            set {
                this.sendSmsField = value;
                this.RaisePropertyChanged("sendSms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool receiveSms {
            get {
                return this.receiveSmsField;
            }
            set {
                this.receiveSmsField = value;
                this.RaisePropertyChanged("receiveSms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool canAccessTwitter {
            get {
                return this.canAccessTwitterField;
            }
            set {
                this.canAccessTwitterField = value;
                this.RaisePropertyChanged("canAccessTwitter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool tracking {
            get {
                return this.trackingField;
            }
            set {
                this.trackingField = value;
                this.RaisePropertyChanged("tracking");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool isAdmin {
            get {
                return this.isAdminField;
            }
            set {
                this.isAdminField = value;
                this.RaisePropertyChanged("isAdmin");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iridiumgo.lan/sdk/")]
    public partial class sdk_task_perform_Result_t : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int taskIDField;
        
        private int responseCodeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int taskID {
            get {
                return this.taskIDField;
            }
            set {
                this.taskIDField = value;
                this.RaisePropertyChanged("taskID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iridiumgo.lan/sdk/")]
    public partial class sdk_task_perform_response_t : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorField;
        
        private string errorMessageField;
        
        private sdk_task_perform_Result_t[] taskResultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("taskResults", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public sdk_task_perform_Result_t[] taskResults {
            get {
                return this.taskResultsField;
            }
            set {
                this.taskResultsField = value;
                this.RaisePropertyChanged("taskResults");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iridiumgo.lan/sdk/")]
    public partial class sdk_task_request_t : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int taskIDField;
        
        private sdk_generic_option_t[] optionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int taskID {
            get {
                return this.taskIDField;
            }
            set {
                this.taskIDField = value;
                this.RaisePropertyChanged("taskID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("options", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public sdk_generic_option_t[] options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
                this.RaisePropertyChanged("options");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iridiumgo.lan/sdk/")]
    public partial class sdk_generic_option_t : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        private string dataTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
                this.RaisePropertyChanged("dataType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iridiumgo.lan/sdk/")]
    public partial class sdk_configuration_set_Result_t : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tagField;
        
        private int errorField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
                this.RaisePropertyChanged("tag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iridiumgo.lan/sdk/")]
    public partial class sdk_configuration_setSettings_response_t : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorField;
        
        private string errorMessageField;
        
        private sdk_configuration_set_Result_t[] setResultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("setResults", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public sdk_configuration_set_Result_t[] setResults {
            get {
                return this.setResultsField;
            }
            set {
                this.setResultsField = value;
                this.RaisePropertyChanged("setResults");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iridiumgo.lan/sdk/")]
    public partial class sdk_configuration_setRequst_t : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tagField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
                this.RaisePropertyChanged("tag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iridiumgo.lan/sdk/")]
    public partial class sdk_configuration_t : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tagField;
        
        private string friendlyNameField;
        
        private string dataTypeField;
        
        private string valueField;
        
        private string minValueField;
        
        private string maxValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
                this.RaisePropertyChanged("tag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string friendlyName {
            get {
                return this.friendlyNameField;
            }
            set {
                this.friendlyNameField = value;
                this.RaisePropertyChanged("friendlyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
                this.RaisePropertyChanged("dataType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string minValue {
            get {
                return this.minValueField;
            }
            set {
                this.minValueField = value;
                this.RaisePropertyChanged("minValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string maxValue {
            get {
                return this.maxValueField;
            }
            set {
                this.maxValueField = value;
                this.RaisePropertyChanged("maxValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iridiumgo.lan/sdk/")]
    public partial class sdk_configuration_getSettings_response_t : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorField;
        
        private string errorMessageField;
        
        private sdk_configuration_t[] configurationsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("configurations", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public sdk_configuration_t[] configurations {
            get {
                return this.configurationsField;
            }
            set {
                this.configurationsField = value;
                this.RaisePropertyChanged("configurations");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iridiumgo.lan/sdk/")]
    public partial class sdk_configuration_tagRequest_t : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
                this.RaisePropertyChanged("tag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iridiumgo.lan/sdk/")]
    public partial class sdk_status_t : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iridiumgo.lan/sdk/")]
    public partial class sdk_status_get_response_t : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorField;
        
        private string errorMessageField;
        
        private sdk_status_t[] statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("status", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public sdk_status_t[] status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iridiumgo.lan/sdk/")]
    public partial class sdk_user_details_response_t : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorField;
        
        private string errorMessageField;
        
        private sdk_user_t userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public sdk_user_t user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iridiumgo.lan/sdk/")]
    public partial class sdk_user_credentials_t : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatus", WrapperNamespace="http://iridiumgo.lan/sdk/", IsWrapped=true)]
    public partial class getStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("options", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public IridiumGoManager.IridiumGo.sdk_generic_option_t[] request;
        
        public getStatusRequest() {
        }
        
        public getStatusRequest(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, IridiumGoManager.IridiumGo.sdk_generic_option_t[] request) {
            this.userCredentials = userCredentials;
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatusResponse", WrapperNamespace="http://iridiumgo.lan/sdk/", IsWrapped=true)]
    public partial class getStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public IridiumGoManager.IridiumGo.sdk_status_get_response_t statusOutput;
        
        public getStatusResponse() {
        }
        
        public getStatusResponse(IridiumGoManager.IridiumGo.sdk_status_get_response_t statusOutput) {
            this.statusOutput = statusOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSettings", WrapperNamespace="http://iridiumgo.lan/sdk/", IsWrapped=true)]
    public partial class getSettingsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("requestList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public IridiumGoManager.IridiumGo.sdk_configuration_tagRequest_t[] reqList;
        
        public getSettingsRequest() {
        }
        
        public getSettingsRequest(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, IridiumGoManager.IridiumGo.sdk_configuration_tagRequest_t[] reqList) {
            this.userCredentials = userCredentials;
            this.reqList = reqList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSettingsResponse", WrapperNamespace="http://iridiumgo.lan/sdk/", IsWrapped=true)]
    public partial class getSettingsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public IridiumGoManager.IridiumGo.sdk_configuration_getSettings_response_t configs;
        
        public getSettingsResponse() {
        }
        
        public getSettingsResponse(IridiumGoManager.IridiumGo.sdk_configuration_getSettings_response_t configs) {
            this.configs = configs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setSettings", WrapperNamespace="http://iridiumgo.lan/sdk/", IsWrapped=true)]
    public partial class setSettingsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("setRequests", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public IridiumGoManager.IridiumGo.sdk_configuration_setRequst_t[] setList;
        
        public setSettingsRequest() {
        }
        
        public setSettingsRequest(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, IridiumGoManager.IridiumGo.sdk_configuration_setRequst_t[] setList) {
            this.userCredentials = userCredentials;
            this.setList = setList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setSettingsResponse", WrapperNamespace="http://iridiumgo.lan/sdk/", IsWrapped=true)]
    public partial class setSettingsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setSettingsResponse", Namespace="", Order=0)]
        public IridiumGoManager.IridiumGo.sdk_configuration_setSettings_response_t setSettingsResponse1;
        
        public setSettingsResponse() {
        }
        
        public setSettingsResponse(IridiumGoManager.IridiumGo.sdk_configuration_setSettings_response_t setSettingsResponse1) {
            this.setSettingsResponse1 = setSettingsResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="performTask", WrapperNamespace="http://iridiumgo.lan/sdk/", IsWrapped=true)]
    public partial class performTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("requestList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public IridiumGoManager.IridiumGo.sdk_task_request_t[] taskList;
        
        public performTaskRequest() {
        }
        
        public performTaskRequest(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, IridiumGoManager.IridiumGo.sdk_task_request_t[] taskList) {
            this.userCredentials = userCredentials;
            this.taskList = taskList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="performTaskResponse", WrapperNamespace="http://iridiumgo.lan/sdk/", IsWrapped=true)]
    public partial class performTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public IridiumGoManager.IridiumGo.sdk_task_perform_response_t parameters;
        
        public performTaskResponse() {
        }
        
        public performTaskResponse(IridiumGoManager.IridiumGo.sdk_task_perform_response_t parameters) {
            this.parameters = parameters;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface sdkChannel : IridiumGoManager.IridiumGo.sdk, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class sdkClient : System.ServiceModel.ClientBase<IridiumGoManager.IridiumGo.sdk>, IridiumGoManager.IridiumGo.sdk {
        
        public sdkClient() {
        }
        
        public sdkClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public sdkClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sdkClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sdkClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IridiumGoManager.IridiumGo.sdk_version_t getVersion() {
            return base.Channel.getVersion();
        }
        
        public System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.sdk_version_t> getVersionAsync() {
            return base.Channel.getVersionAsync();
        }
        
        public IridiumGoManager.IridiumGo.sdk_user_details_response_t getUserDetails(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials) {
            return base.Channel.getUserDetails(userCredentials);
        }
        
        public System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.sdk_user_details_response_t> getUserDetailsAsync(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials) {
            return base.Channel.getUserDetailsAsync(userCredentials);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IridiumGoManager.IridiumGo.getStatusResponse IridiumGoManager.IridiumGo.sdk.getStatus(IridiumGoManager.IridiumGo.getStatusRequest request) {
            return base.Channel.getStatus(request);
        }
        
        public IridiumGoManager.IridiumGo.sdk_status_get_response_t getStatus(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, IridiumGoManager.IridiumGo.sdk_generic_option_t[] request) {
            IridiumGoManager.IridiumGo.getStatusRequest inValue = new IridiumGoManager.IridiumGo.getStatusRequest();
            inValue.userCredentials = userCredentials;
            inValue.request = request;
            IridiumGoManager.IridiumGo.getStatusResponse retVal = ((IridiumGoManager.IridiumGo.sdk)(this)).getStatus(inValue);
            return retVal.statusOutput;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.getStatusResponse> IridiumGoManager.IridiumGo.sdk.getStatusAsync(IridiumGoManager.IridiumGo.getStatusRequest request) {
            return base.Channel.getStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.getStatusResponse> getStatusAsync(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, IridiumGoManager.IridiumGo.sdk_generic_option_t[] request) {
            IridiumGoManager.IridiumGo.getStatusRequest inValue = new IridiumGoManager.IridiumGo.getStatusRequest();
            inValue.userCredentials = userCredentials;
            inValue.request = request;
            return ((IridiumGoManager.IridiumGo.sdk)(this)).getStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IridiumGoManager.IridiumGo.getSettingsResponse IridiumGoManager.IridiumGo.sdk.getSettings(IridiumGoManager.IridiumGo.getSettingsRequest request) {
            return base.Channel.getSettings(request);
        }
        
        public IridiumGoManager.IridiumGo.sdk_configuration_getSettings_response_t getSettings(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, IridiumGoManager.IridiumGo.sdk_configuration_tagRequest_t[] reqList) {
            IridiumGoManager.IridiumGo.getSettingsRequest inValue = new IridiumGoManager.IridiumGo.getSettingsRequest();
            inValue.userCredentials = userCredentials;
            inValue.reqList = reqList;
            IridiumGoManager.IridiumGo.getSettingsResponse retVal = ((IridiumGoManager.IridiumGo.sdk)(this)).getSettings(inValue);
            return retVal.configs;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.getSettingsResponse> IridiumGoManager.IridiumGo.sdk.getSettingsAsync(IridiumGoManager.IridiumGo.getSettingsRequest request) {
            return base.Channel.getSettingsAsync(request);
        }
        
        public System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.getSettingsResponse> getSettingsAsync(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, IridiumGoManager.IridiumGo.sdk_configuration_tagRequest_t[] reqList) {
            IridiumGoManager.IridiumGo.getSettingsRequest inValue = new IridiumGoManager.IridiumGo.getSettingsRequest();
            inValue.userCredentials = userCredentials;
            inValue.reqList = reqList;
            return ((IridiumGoManager.IridiumGo.sdk)(this)).getSettingsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IridiumGoManager.IridiumGo.setSettingsResponse IridiumGoManager.IridiumGo.sdk.setSettings(IridiumGoManager.IridiumGo.setSettingsRequest request) {
            return base.Channel.setSettings(request);
        }
        
        public IridiumGoManager.IridiumGo.sdk_configuration_setSettings_response_t setSettings(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, IridiumGoManager.IridiumGo.sdk_configuration_setRequst_t[] setList) {
            IridiumGoManager.IridiumGo.setSettingsRequest inValue = new IridiumGoManager.IridiumGo.setSettingsRequest();
            inValue.userCredentials = userCredentials;
            inValue.setList = setList;
            IridiumGoManager.IridiumGo.setSettingsResponse retVal = ((IridiumGoManager.IridiumGo.sdk)(this)).setSettings(inValue);
            return retVal.setSettingsResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.setSettingsResponse> IridiumGoManager.IridiumGo.sdk.setSettingsAsync(IridiumGoManager.IridiumGo.setSettingsRequest request) {
            return base.Channel.setSettingsAsync(request);
        }
        
        public System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.setSettingsResponse> setSettingsAsync(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, IridiumGoManager.IridiumGo.sdk_configuration_setRequst_t[] setList) {
            IridiumGoManager.IridiumGo.setSettingsRequest inValue = new IridiumGoManager.IridiumGo.setSettingsRequest();
            inValue.userCredentials = userCredentials;
            inValue.setList = setList;
            return ((IridiumGoManager.IridiumGo.sdk)(this)).setSettingsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IridiumGoManager.IridiumGo.performTaskResponse IridiumGoManager.IridiumGo.sdk.performTask(IridiumGoManager.IridiumGo.performTaskRequest request) {
            return base.Channel.performTask(request);
        }
        
        public IridiumGoManager.IridiumGo.sdk_task_perform_response_t performTask(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, IridiumGoManager.IridiumGo.sdk_task_request_t[] taskList) {
            IridiumGoManager.IridiumGo.performTaskRequest inValue = new IridiumGoManager.IridiumGo.performTaskRequest();
            inValue.userCredentials = userCredentials;
            inValue.taskList = taskList;
            IridiumGoManager.IridiumGo.performTaskResponse retVal = ((IridiumGoManager.IridiumGo.sdk)(this)).performTask(inValue);
            return retVal.parameters;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.performTaskResponse> IridiumGoManager.IridiumGo.sdk.performTaskAsync(IridiumGoManager.IridiumGo.performTaskRequest request) {
            return base.Channel.performTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.performTaskResponse> performTaskAsync(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, IridiumGoManager.IridiumGo.sdk_task_request_t[] taskList) {
            IridiumGoManager.IridiumGo.performTaskRequest inValue = new IridiumGoManager.IridiumGo.performTaskRequest();
            inValue.userCredentials = userCredentials;
            inValue.taskList = taskList;
            return ((IridiumGoManager.IridiumGo.sdk)(this)).performTaskAsync(inValue);
        }
        
        public IridiumGoManager.IridiumGo.sdk_user_getList_Response_t getUserList(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials) {
            return base.Channel.getUserList(userCredentials);
        }
        
        public System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.sdk_user_getList_Response_t> getUserListAsync(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials) {
            return base.Channel.getUserListAsync(userCredentials);
        }
        
        public IridiumGoManager.IridiumGo.sdk_user_add_modify_remove_Response_t addModifyUser(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, IridiumGoManager.IridiumGo.sdk_user_t user) {
            return base.Channel.addModifyUser(userCredentials, user);
        }
        
        public System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.sdk_user_add_modify_remove_Response_t> addModifyUserAsync(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, IridiumGoManager.IridiumGo.sdk_user_t user) {
            return base.Channel.addModifyUserAsync(userCredentials, user);
        }
        
        public IridiumGoManager.IridiumGo.sdk_user_add_modify_remove_Response_t removeUser(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, string userName) {
            return base.Channel.removeUser(userCredentials, userName);
        }
        
        public System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.sdk_user_add_modify_remove_Response_t> removeUserAsync(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, string userName) {
            return base.Channel.removeUserAsync(userCredentials, userName);
        }
        
        public IridiumGoManager.IridiumGo.sdk_contacts_getList_Response_t getContactList(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials) {
            return base.Channel.getContactList(userCredentials);
        }
        
        public System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.sdk_contacts_getList_Response_t> getContactListAsync(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials) {
            return base.Channel.getContactListAsync(userCredentials);
        }
        
        public IridiumGoManager.IridiumGo.sdk_contact_add_modify_remove_Response_t addNewContact(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, string name, string number, bool isFavourite) {
            return base.Channel.addNewContact(userCredentials, name, number, isFavourite);
        }
        
        public System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.sdk_contact_add_modify_remove_Response_t> addNewContactAsync(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, string name, string number, bool isFavourite) {
            return base.Channel.addNewContactAsync(userCredentials, name, number, isFavourite);
        }
        
        public IridiumGoManager.IridiumGo.sdk_contact_add_modify_remove_Response_t modifyContact(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, IridiumGoManager.IridiumGo.sdk_contact_t contact) {
            return base.Channel.modifyContact(userCredentials, contact);
        }
        
        public System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.sdk_contact_add_modify_remove_Response_t> modifyContactAsync(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, IridiumGoManager.IridiumGo.sdk_contact_t contact) {
            return base.Channel.modifyContactAsync(userCredentials, contact);
        }
        
        public IridiumGoManager.IridiumGo.sdk_contact_add_modify_remove_Response_t removeContact(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, int contactID) {
            return base.Channel.removeContact(userCredentials, contactID);
        }
        
        public System.Threading.Tasks.Task<IridiumGoManager.IridiumGo.sdk_contact_add_modify_remove_Response_t> removeContactAsync(IridiumGoManager.IridiumGo.sdk_user_credentials_t userCredentials, int contactID) {
            return base.Channel.removeContactAsync(userCredentials, contactID);
        }
    }
}
